In [1]:
import numpy as np





In [2]:
data1 = [6,7.5,8,0,1]





In [3]:
# 새로운 array 생성
arr1 = np.array(data1)
arr1





array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# arr1의 크기 확인
arr1.shape





(5,)

In [5]:
# 2차원 array 생성
data2 = [
[1,2,3,4],
[5,6,7,8]
]





In [6]:
arr2 = np.array(data2)
arr2





array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape #2행 4열이다





(2, 4)

In [8]:
# 0으로만 구성된 array 생성 - 3행 6열 짜리 !
np.zeros([3,6]) 





array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# 범위가 있는 array 생성
np.arange(15)





array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(1,10)





array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)





array([1, 3, 5, 7, 9])

In [12]:
type(arr1)





numpy.ndarray

In [13]:
arr1.dtype #데이터타입을 알려줌





dtype('float64')

----------------------------------------------

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1





array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2





array([[ 7,  8,  9],
       [10, 11, 12]])

# array 연산

In [16]:
# 더하기 - 각 요소들의 값을 다 더함
arr1 + arr2
# 빼기
arr1 - arr2
#등 사칙연산





array([[-6, -6, -6],
       [-6, -6, -6]])

In [17]:
# 숫자를 대입한 array 연산
arr1*3





array([[ 3,  6,  9],
       [12, 15, 18]])

In [18]:
#루트?
arr1 ** 0.5





array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [19]:
arr3 = 1 / arr1





In [20]:
arr3





array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])