In [1]:
import numpy as np





In [2]:
# 1부터 9까지의 array 만들기
arr = np.arange(1,10)





In [3]:
arr





array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# root 값 - 값들이 루트로 계산됨
np.sqrt(arr)





array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
# sin값 구하기
np.sin(arr)





array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [6]:
#소숫점 아래 7자리 랜덤
x = np.random.rand(8)
x





array([0.99758444, 0.09233628, 0.71146591, 0.78439733, 0.20005762,
       0.29151128, 0.07637167, 0.03410161])

In [7]:
#랜덤값을 최초에 받고 바뀌지 않게 하는법 seed





In [8]:
np.random.seed(0)
x = np.random.rand(8)
y = np.random.rand(8)





print(x)
print(y)

In [9]:
# x, y array 값들중 최대값으로 구성된 array 만들기 - 인덱스 x[0][0] 과 y[0][0] 같이 같은자리 값을 비교해서 최댓값 출력
np.maximum(x,y)





array([0.96366276, 0.71518937, 0.79172504, 0.54488318, 0.56804456,
       0.92559664, 0.43758721, 0.891773  ])

# numpy 에서 제공하는 통계함수

In [10]:
arr = np.random.rand(5,4)





In [11]:
arr





array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]])

In [12]:
# 출력된 리스트의 전체 합을 구하기
arr.sum()





11.003319380705765

In [13]:
# 전체 평균 구하기
arr.mean()





0.5501659690352882

In [14]:
arr.sum()/arr.mean()





20.0

In [15]:
# arr의 열별로 합을 구하기
arr.sum(axis = 0)





array([2.09510982, 3.25479532, 1.66633481, 3.98707943])

In [16]:
# arr의 행별로 합을 구하기
arr.sum(axis = 1)





array([2.50100714, 3.01978544, 1.84621765, 1.97529956, 1.66100958])

In [17]:
# arr 중에서 0.3초과인 것의 갯수
arr > 0.3





array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True]])

In [18]:
# true일땐 1이기 때문에 모두 합하면 갯수를 알 수 있음
(arr > 0.3).sum()





15

In [19]:
ints = np.array([3,3,2,2,1,1])





In [20]:
# 중복값 제거
np.unique(ints)





array([1, 2, 3])